name: deepsort_track
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.1.1=pyhd8ed1ab_0
  - python=3.6.13
  - wheel=0.36.2=pyhd3deb0d_0
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - bounding-box==0.1.3
    - cached-property==1.5.2
    - dataclasses==0.8
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.37.1
    - h5py==2.9.0
    - importlib-metadata==4.0.1
    - joblib==1.0.1
    - keras==2.2.5
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - numpy==1.19.5
    - opencv-python==4.5.2.52
    - opt-einsum==3.3.0
    - pillow==8.2.0
    - protobuf==3.16.0
    - pyyaml==5.4.1
    - scikit-learn==0.22.2
    - scipy==1.5.4
    - six==1.16.0
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - typing-extensions==3.10.0.0
    - werkzeug==2.0.0
    - wget==3.2
    - wrapt==1.12.1
    - zipp==3.4.1
